# Setting up Travis CI:

# 1. Go to https://travis-ci.org
# 2. Click the Sign Up/Sign in with GitHub button and give Travis CI permission
#    to access your GitHub repositories.
# 3. Create a file like this one you're reading at `your-rails-app/.travis.yml`:

language: ruby
rvm:
  - 2.5.3
  # Add more Ruby versions to list if supported,
  # Travis supports these versions: http://rubies.travis-ci.org/

addons:
  firefox: "38.0.5" # Set Firefox Version if needed.

# If needed, use xvfb to setup fake monitor display so Firefox GUI can be used by specs:
# http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
# before_install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"

# 4. OPTIONAL Only customize the `script` option if needed.

# The `script` option is an optional list of the main build task(s). `rake` is
# the default script option for Travis and most Rails projects will want this
# when starting out as this usually runs `rake test`.

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake

# 5. OPTIONAL Add a Build Status Badge to your README, follow instructions here:
#    http://docs.travis-ci.com/user/status-images/

# Suggested docs
# --------------
# Getting Started: http://docs.travis-ci.com/user/getting-started/
# Ruby & Travis CI docs: http://docs.travis-ci.com/user/languages/ruby/
# Supported Ruby Versions: http://rubies.travis-ci.org/
# Custom build task: http://docs.travis-ci.com/user/customizing-the-build/
# GUI, Browsers, xvfb: http://docs.travis-ci.com/user/gui-and-headless-browsers/
