language: ruby
rvm:
  - 2.5.3
  - 2.3.0
  - 2.2.4
bundler_args: --jobs=2

script:
  - bundle exec rake db:setup
  - bundle exec rake spec

cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"